apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dotnetcore-app-dev
  namespace: openshift-gitops
spec:
  destination:
    namespace: dotnetcore-app-dev
    server: https://kubernetes.default.svc 
  project: default 
  source: 
    path: environments/dev
    repoURL: https://github.com/NandaHein/dotnetcore-gitops.git
    targetRevision: develop
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
