apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../k8s/
images:
- digest: sha256:a4a29150d2ffc25bd18a48f08ce3350ea67cba7ab1679d8eb6b58153494803ec
  name: quay.io/nandahein/dotnetcore
  newName: quay.io/nandahein/dotnetcore
- digest: sha256:ed7164b840f398122175ec730d5499160412209b322f7b8a09fc71a09b25e0ec
  name: quay.io/rh-ee-srehman/dotnetcore
  newName: quay.io/rh-ee-srehman/dotnetcore
